+---+------+
| id|  type|
+---+------+
| 97|vertex|
| 27|vertex|
| 58|vertex|
| 80|vertex|
| 28|vertex|
| 40|vertex|
|101|vertex|
|105|vertex|
| 98|vertex|
| 48|vertex|
| 51|vertex|
| 93|vertex|
| 44|vertex|
| 83|vertex|
|118|vertex|
|113|vertex|
| 45|vertex|
| 61|vertex|
|127|vertex|
| 72|vertex|
+---+------+
only showing top 20 rows

+---+---+
|src|dst|
+---+---+
| 54|137|
| 88| 50|
|  1| 41|
| 41| 91|
|115|133|
|  2| 73|
|120| 26|
| 33|111|
| 93|127|
|107| 34|
|139|130|
|133|131|
| 54| 21|
| 93| 86|
| 38| 22|
|126| 42|
| 42| 58|
|  7| 34|
| 34| 35|
|  4|137|
+---+---+
only showing top 20 rows

+---+------+-------------------+
| id|  type|           pagerank|
+---+------+-------------------+
| 80|vertex|  2.051449022235358|
| 58|vertex|  1.857655751296856|
| 97|vertex| 1.1255851464441422|
| 28|vertex| 0.6584098162850707|
| 27|vertex| 0.6502752374405787|
|105|vertex| 0.7367772936522936|
| 98|vertex| 0.6000672359830829|
| 48|vertex| 0.8899811847903953|
| 40|vertex| 0.9912601235161947|
|101|vertex| 1.0324664695597372|
|118|vertex|0.48171706190391894|
| 83|vertex| 0.8674462038551595|
| 51|vertex| 0.9172517566906516|
| 44|vertex|  0.482276502077713|
| 93|vertex| 0.8146452724205298|
|113|vertex| 0.7672151281894894|
| 61|vertex| 0.5069775705017016|
| 45|vertex| 0.5516801694474108|
| 72|vertex| 0.9920216881436567|
|127|vertex| 0.5983108405786284|
+---+------+-------------------+
only showing top 20 rows

None
Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o144.csv.
: org.apache.spark.sql.AnalysisException: path hdfs://ip-172-31-10-90.ec2.internal:8020/user/hadoop/email-enron.txt.csv already exists.;
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:123)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:173)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:169)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:197)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:194)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:169)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:114)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:112)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:696)
	at org.apache.spark.sql.execution.SQLExecution$.org$apache$spark$sql$execution$SQLExecution$$executeQuery$1(SQLExecution.scala:83)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1$$anonfun$apply$1.apply(SQLExecution.scala:94)
	at org.apache.spark.sql.execution.QueryExecutionMetrics$.withMetrics(QueryExecutionMetrics.scala:141)
	at org.apache.spark.sql.execution.SQLExecution$.org$apache$spark$sql$execution$SQLExecution$$withMetrics(SQLExecution.scala:178)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:93)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:200)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:92)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:696)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:305)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:291)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:249)
	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:684)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hadoop/hypergraph-study/clique_page_rank.py", line 56, in <module>
    results2.vertices.write.csv(sys.argv[1] + ".csv")
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 932, in csv
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 69, in deco
pyspark.sql.utils.AnalysisException: 'path hdfs://ip-172-31-10-90.ec2.internal:8020/user/hadoop/email-enron.txt.csv already exists.;'
